### PR TITLE
fix: domWrapper.d.ts imports

### PR DESCRIPTION
**Pull request by alfeg**
Fix for issue #936 
Created issue, then realized that fix is quite simple.

### CODE REVIEW

**Review by cexbrayat — APPROVED** [review]
Thanks @alfeg !

**Comment by cj848** [comment]
When will this issue be released? In my project the build is not working because of that problem.

**Comment by cexbrayat** [comment]
A release should occur soon.

In the meantime check the workaround here https://github.com/vuejs/vue-test-utils-next/issues/936#issuecomment-916844985

**Comment by cj848** [comment]
The same option came to my mind and applied.
However, for users who have not applied this option, please release it as soon as possible. Thank you.

**Pull request merged**
