### PR TITLE
docs: fixed a typo in vue-router.md

### PR DESCRIPTION
**Pull request by sonagi784**

### CODE REVIEW

**Review by cexbrayat — APPROVED** [review]
Thanks!

**Comment by sonagi784** [comment]
oh, I used wrong account.. can i open again?

**Comment by sonagi784** [comment]
> Thanks!

oh, I used wrong account.. can i open again?

**Comment by cexbrayat** [comment]
Sure!

**Comment by sonagi784** [comment]
thank you

**Pull request closed without merging**
