### PR TITLE
chore: bump to Vue 3.0.0-beta.15

### PR DESCRIPTION
**Pull request by cexbrayat**

### CODE REVIEW

**Comment by cexbrayat** [comment]
@pikax If you don't mind, I'd like your opinion on the failing dts test:
```typescript
// no data provided
expectError(
  mount(AppWithDefine, {
    data() {
      return {
        myVal: 1
      }
    }
  })
)
```
is not throwing error with `beta.15` whereas it was when you introduced it. Is there something we need to change in our `mount` signatures or is it normal that this does not fail anymore with mixins and entends?

**Comment by lmiller1990** [comment]
This is just a types error that is breaking things yeah? What changed in Vue core 🤔

**Comment by cexbrayat** [comment]
@lmiller1990 Nothing major, but it looks like we lost a bit of inference. Not a big deal, I just want to make sure we're not mising something ;)

**Comment by cexbrayat** [comment]
@pikax Thanks for your help!

@lmiller1990 If that's OK with you, we can merge and I'll take care of removing the TODO when https://github.com/vuejs/vue-next/pull/1361 is merged and released (I hope it will make it in `beta.16`). Or we can wait for beta.16, as you wish

**Comment by lmiller1990** [comment]
Seems like it's fine to wait - this PR isn't blocking anything. 

Thanks for this!

**Comment by lmiller1990** [comment]
Looks like we are good to merge yeah @cexbrayat ?

**Comment by cexbrayat** [comment]
👍 I'll remove the TODO when `beta.16` will be out

**Pull request merged**
