### PR TITLE
Export MountingOptions interface

### PR DESCRIPTION
**Pull request by afontcu**
Having `MountingOptions` available in Vue Testing Library will improve greatly the DX of people using the library.

### CODE REVIEW

**Review by dobromir-hristov — APPROVED** [review]

**Review by pikax — APPROVED** [review]

**Review by cexbrayat — APPROVED** [review]
👍 If it's now public, we could even add documentation on each option (they would show up in IDE)

**Comment by afontcu** [comment]
> 👍 If it's now public, we could even add documentation on each option (they would show up in IDE)

Sure, that'd be great!

However, it is not related to making the interface public, right? As far as I know, people using VTU is already "seeing" the outputs of the interface.

**Comment by cexbrayat** [comment]
Right, but it's a good rule of thumb that exported types should be documented. I'm fine merging it like this though, it was just nitpicking :)

**Comment by afontcu** [comment]
no prob! I'll update this with some documentation :)

**Comment by afontcu** [comment]
Done! Decided to move type into `types.ts` file because it grew a lot.

**Comment by cexbrayat** [comment]
@afontcu 👏 thank you for taking the time to do this! LGTM

**Comment by afontcu** [comment]
totally worth it! It also helped me identify several missing keys in our docs. Working on it now.

**Review by lmiller1990 — APPROVED** [review]
true beauty is documenting each type

**Comment by scottbedard** [comment]
@afontcu Thank you for this! This makes building custom `mount` functions much nicer!

**Pull request merged**
