### PR TITLE
Bump Vue to 3.0.4

### LINKED ISSUE #278: Update to 3.0.4 and 3.0.5
As of Vue 3.0.4 this test is broken: https://github.com/vuejs/vue-test-utils-next/blob/c5d31307fe2dbd9bb04c3af3287cae93920014af/tests/mountingOptions/stubs.global.spec.ts#L348

Todo: find out why.

### PR DESCRIPTION
**Pull request by afontcu**
Closes #278.

Nothing to see here, yet – I'm on it, but I wanted to open a draft PR in case anyone was working on it, too.

So far, this is what I could track down from vue-next:

rawChildren is null here: https://github.com/vuejs/vue-next/blob/3bc2914e32b030b1247659f871f6055827154087/packages/runtime-core/src/componentRenderUtils.ts#L230

This appears to be the offending commit, putting back highlighted lines makes test pass again: https://github.com/vuejs/vue-next/commit/3bc2914e32b030b1247659f871f6055827154087#diff-3f88622d34d4d3a0b6e44ddd42967279cc0d25f817d6f17fad79ae4b205c405eL225-L227

### CODE REVIEW

**Comment by afontcu** [comment]
Okay, I believe https://github.com/vuejs/vue-next/pull/2750 will fix this up. Shall we wait for 3.0.5, then?

**Comment by lmiller1990** [comment]
Oh, great! Let's wait for 3.0.5. I lost quite a few hours debugging this one too. Glad someone has found the bug.

**Comment by afontcu** [comment]
Looks like the PR [didn't make it to 3.0.5](https://github.com/vuejs/vue-next/compare/v3.0.4...v3.0.5), we'll need to wait a bit longer 😉

**Comment by cexbrayat** [comment]
Closing this one as we are now up-to-date with vue-next 3.0.6

**Comment by lmiller1990** [comment]
Thanks!

**Pull request closed without merging**
