### PR TITLE
wip: class component support

### PR DESCRIPTION
**Pull request by lmiller1990**
Class component is not working when declared in a SFC file.

https://github.com/vuejs/vue-jest/issues/297 related maybe.

I will continue adding more test cases here.

### CODE REVIEW

**Comment by lmiller1990** [comment]
SFC support is blocked by vue-jest. I will address it on the weekend.

Then we should be good for class component 👍

**Comment by Stijn98s** [comment]
@lmiller1990 need any help on this this weekend?

**Comment by lmiller1990** [comment]
Think I've got it covered, I will tag you when I have something up for some help/testing - most of the complexity is in vue-jest.

**Comment by lmiller1990** [comment]
Ok, this will pass when https://github.com/vuejs/vue-jest/pull/300 is released. vue-jest is blocking class components in SFC files.

**Pull request merged**
