### PR TITLE
(wip) feat: move docs to main repo using Vitepress

### PR DESCRIPTION
**Pull request by lmiller1990**
It's coming

### CODE REVIEW

**Comment by lmiller1990** [comment]
Problem is Jekyll ignores `_` files, we can use a Jekyll ignore file.

**Comment by afontcu** [comment]
Cool! 🚀  Do we need to commit autogenerated files, though? We could move docs infra to Netlify, and just set the build command, so that Netlify handles the build process and deploys the right version.

**Comment by lmiller1990** [comment]
notes for myself

```
vi node_modules/vitepress/dist/client/theme-default/components/SideBar.js
```

```
function resolveMultiSidebar(config, path, headers, depth) {
    const paths = [
        path,
        Object.keys(config)[0]
    ]
    const item = paths.map(x=>config[getPathDirName(x)]).find(Boolean)

    if (Array.isArray(item)) {
        return resolveArraySidebar(item, depth);
    }
    if (item === 'auto') {
        return resolveAutoSidebar(headers, depth);
    }
    return [];
}
```

**Comment by lmiller1990** [comment]
IT KIND OF WORKS. But not really, still some 404s, and I had to hack vitepress. https://vuejs.github.io/vue-test-utils-next/guide/installation.html

**Comment by lmiller1990** [comment]
Unhill battle. I will come back to this when Vite is more ready.

**Pull request closed without merging**
