### PR TITLE
Bump Vue-related deps

### PR DESCRIPTION
**Pull request by afontcu**
Also silent expected `console.error` messages so that the test output is a bit cleaner.

### CODE REVIEW

**Comment by afontcu** [comment]
build fails due to

`
Error: /home/runner/work/vue-test-utils-next/vue-test-utils-next/src/components/RouterLinkStub.ts(4,14):`
`semantic error TS4023: Exported variable 'RouterLinkStub' has or is using name 'ComponentOptionsBase' from external module "/home/runner/work/vue-test-utils-next/vue-test-utils-next/node_modules/@vue/runtime-core/dist/runtime-core" but cannot be named.
`

🤔  https://github.com/vuejs/vue-test-utils-next/runs/625177043?check_suite_focus=true#step:7:20

**Comment by pikax** [comment]
That's an known issue :(

we need to wait for beta.5 https://github.com/vuejs/vue-next/commit/8ab44e1f80acc79b70cfc9df835aa83e7445f583

**Comment by lmiller1990** [comment]
Looks like beta 5 is available - someone want to try updating this?

**Comment by afontcu** [comment]
sure, will do today!

**Comment by afontcu** [comment]
Looks like this typing test is failing (meaning it is not throwing) now: 

https://github.com/vuejs/vue-test-utils-next/blob/bump-deps/test-dts/mount.d-test.ts#L28

**Comment by afontcu** [comment]
There's also this error highlighted in my IDE, same faile line 58:

`AppWithProps: No overload matches this call.`

Not sure if related

**Pull request merged**
